# Generated by Django 3.2.3 on 2021-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='picture',
            field=models.ImageField(blank=True, upload_to='D:\\PYTHON\\PythonProjects\\Django-api\\myapi\\media'),
        ),
    ]
